version: "2.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./etc/config/elastisearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200

  library:
    image: golang:1.16
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - ./:/go/src/library
      - ./logs/:/logs/
    working_dir: /go/src/library
    environment:
      - PORT=1323
      - DSN=library:password@tcp(mysql.c8ajbiky1mzj.ap-southeast-1.rds.amazonaws.com:3306)/library
      - GOODREAD_APIKEY=6qVbqOjnzhHws97M5gYYA
      - ISBNDB_APIKEY=46384_fe2f7c5150354b92aa708a8e0fa46463
    command: bash -c "go build . && ./library"
    ports:
      - 1323:1323

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.3
    command: filebeat -e -strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./etc/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601
    environment:
      - SERVER_MAXPAYLOADBYTES=20971520

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./etc/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    depends_on:
      - golang
