// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "library/entities"

	mock "github.com/stretchr/testify/mock"
)

// IdbService is an autogenerated mock type for the IdbService type
type IdbService struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *IdbService) Get(_a0 context.Context, _a1 string, _a2 string) (*entities.Book, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *entities.Book
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Book); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *IdbService) List(_a0 context.Context, _a1 int64, _a2 int64, _a3 string) ([]*entities.Book, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []*entities.Book
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) []*entities.Book); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9, _a10, _a11, _a12, _a13, _a14
func (_m *IdbService) Upsert(_a0 context.Context, _a1 string, _a2 string, _a3 string, _a4 string, _a5 string, _a6 string, _a7 string, _a8 string, _a9 string, _a10 string, _a11 string, _a12 int64, _a13 int64, _a14 int64) (*entities.Book, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9, _a10, _a11, _a12, _a13, _a14)

	var r0 *entities.Book
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string, string, string, string, int64, int64, int64) *entities.Book); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9, _a10, _a11, _a12, _a13, _a14)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string, string, string, string, string, int64, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8, _a9, _a10, _a11, _a12, _a13, _a14)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
